name: Integration Test CI

on:
  push:
    branches:
      - main
      - staging
      - development
  pull_request:
    branches:
      - main
      - staging
      - development
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

  
    - name: Install dependencies
      run: npm install

 
    - name: Run tests
      run: npm run test

  
    - name:  Check code coverage
      run: npm run test:coverage

 

