name: PR Reminder (6 Hours)

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find PRs with pending review comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PRS=$(gh pr list --json number,author,updatedAt,state --jq \
          '.[] | select(.state=="OPEN") | select((now - ( .updatedAt | fromdateiso8601 )) > 21600) | .number')

          for PR_NUMBER in $PRS; do
            echo "Checking PR #$PR_NUMBER"

            REVIEW_COMMENTS=$(gh pr view $PR_NUMBER --json reviewComments --jq '.reviewComments | length')

            if [ "$REVIEW_COMMENTS" -gt 0 ]; then
              PR_AUTHOR=$(gh pr view $PR_NUMBER --json author --jq '.author.login')
              echo "PR #$PR_NUMBER has pending reviews. Notifying @$PR_AUTHOR"

              gh pr comment $PR_NUMBER --body "Hey @$PR_AUTHOR, your PR has pending review comments for more than 6 hours. Please address them soon!"
            fi
          done
